/* Domain vocabulary boosted by Deepgram nova-3 keyterm prompting so the voice
   features transcribe rocket propulsion / fluid-network jargon accurately.
   Shared by the dictation recorder (ConversationRecorder) and the conversational
   Copilot (VoiceAgentCopilot). Multi-word entries are kept as single phrases so
   they boost as a cohesive unit. */
export const ROCKET_KEYTERMS: string[] = [
  "Propellant",
  "Oxidizer",
  "fuel",
  "LOX",
  "OX",
  "RP-1",
  "LN2",
  "GOX",
  "pressurant",
  "ullage",
  "mdot",
  "vdot",
  "Mass flow rate",
  "Volumetric flow rate",
  "Pressure drop",
  "dp",
  "Line loss",
  "Back pressure",
  "Choked flow",
  "Compressible flow",
  "Incompressible flow",
  "Two-phase flow",
  "Vapor pressure",
  "Boiloff",
  "Density",
  "rho",
  "helium",
  "nitrogen",
  "GN2",
  "cryo",
  "cryogenics",
  "MR",
  "pressurization",
  "fuel-rich",
  "ox-rich",
  "ox-tank",
  "fuel-tank",
  "COPV",
  "Regulator",
  "reg",
  "Pressure relief valve",
  "Burst disk",
  "Check valve",
  "Vent",
  "Fill",
  "drain",
  "iso",
  "iso valve",
  "solenoid valve",
  "orifice",
  "manifold",
  "blowdown",
  "chamber pressure",
  "nozzle",
  "throat",
  "injector",
  "P&ID",
];
